# This is a basic workflow to help you get started with Actions

name: Cloudflare DNS Update

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_TOKEN: ${{ secrets.CF_TOKEN }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dns-update:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        shell: bash
        working-directory: ./

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: chmod +x run.sh && ./run.sh
